workflows:
  build-android:
    name: Build Android APK
    environment:
      flutter: "3.19.6"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
