workflows:
  build-android:
    name: Build Solo Leveling APK
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android_signing:
        keystore_reference: YOUR_KEYSTORE_REFERENCE  # تقدر تشيله لو مش هتستخدم توقيع
      vars:
        PACKAGE_NAME: "com.example.sololeveling"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - omareno818@gmail.com
